export const GET_ALLTIME_RECIPE_START = "GET_ALLTIME_RECIPE_START";
export const GET_ALLTIME_RECIPE_SUCCESS = "GET_ALLTIME_RECIPE_SUCCESS";
export const GET_ALLTIME_RECIPE_FAILURE = "GET_ALLTIME_RECIPE_FAILURE";
export const RESET_ALLTIME_RECIPE_STATE = "RESET_ALLTIME_RECIPE_STATE";

export const GET_TODAY_RECIPE_START = "GET_TODAY_RECIPE_START";
export const GET_TODAY_RECIPE_SUCCESS = "GET_TODAY_RECIPE_SUCCESS";
export const GET_TODAY_RECIPE_FAILURE = "GET_TODAY_RECIPE_FAILURE";
export const RESET_TODAY_RECIPE_STATE = "RESET_TODAY_RECIPE_STATE";

export const GET_THISWEEK_RECIPE_START = "GET_THISWEEK_RECIPE_START";
export const GET_THISWEEK_RECIPE_SUCCESS = "GET_THISWEEK_RECIPE_SUCCESS";
export const GET_THISWEEK_RECIPE_FAILURE = "GET_THISWEEK_RECIPE_FAILURE";
export const RESET_THISWEEK_RECIPE_STATE = "RESET_THISWEEK_RECIPE_STATE";

export const GET_THISMONTH_RECIPE_START = "GET_THISMONTH_RECIPE_START";
export const GET_THISMONTH_RECIPE_SUCCESS = "GET_THISMONTH_RECIPE_SUCCESS";
export const GET_THISMONTH_RECIPE_FAILURE = "GET_THISMONTH_RECIPE_FAILURE";
export const RESET_THISMONTH_RECIPE_STATE = "RESET_THISMONTH_RECIPE_STATE";
