export const ADD_RECIPE_START = "ADD_RECIPE_START";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const ADD_RECIPE_FAILURE = "ADD_RECIPE_FAILURE";

export const POST_COMMENT_START = "POST_COMMENT_START";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const GET_COMMENT_START = "GET_COMMENT_START";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";

export const POST_REPLY_START = "POST_REPLY_START";
export const POST_REPLY_SUCCESS = "POST_REPLY_SUCCESS";
export const POST_REPLY_FAILURE = "POST_REPLY_FAILURE";

export const GET_RECIPE_DETAIL_START = "GET_RECIPE_DETAIL_START";
export const GET_RECIPE_DETAIL_SUCCESS = "GET_RECIPE_DETAIL_SUCCESS";
export const GET_RECIPE_DETAIL_FAILURE = "GET_RECIPE_DETAIL_FAILURE";
